### ISSUE TITLE
When reaching max_lease_ttl 5m  application shows warning message for mysql example.

### ISSUE THREAD

**Issue by thatsk** [ivangfr/springboot-vault-examples#1]
@ivangfr  https://github.com/spring-cloud/spring-cloud-vault/issues/557
```
022-01-07 12:44:27.943  WARN 203724 --- [g-Cloud-Vault-2] LeaseEventPublisher$LoggingErrorListener : [RequestedSecret [path='database/creds/student-role', mode=RENEW]] Lease [leaseId='database/creds/student-role/BQvurRJy0eccrDDM1DdmqcU5', leaseDuration=PT10S, renewable=true] Cannot renew lease: Status 400 Bad Request lease not found; nested exception is org.springframework.vault.VaultException: Status 400 Bad Request: lease not found; nested exception is org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"errors":["lease not found"]}<LF>"

org.springframework.vault.VaultException: Cannot renew lease: Status 400 Bad Request lease not found; nested exception is org.springframework.vault.VaultException: Status 400 Bad Request: lease not found; nested exception is org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"errors":["lease not found"]}<LF>"
	at org.springframework.vault.core.lease.SecretLeaseContainer.doRenewLease(SecretLeaseContainer.java:694) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.lease.SecretLeaseContainer.renewAndSchedule(SecretLeaseContainer.java:577) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.lease.SecretLeaseContainer.lambda$scheduleLeaseRenewal$2(SecretLeaseContainer.java:569) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.lease.SecretLeaseContainer$LeaseRenewalScheduler$1.run(SecretLeaseContainer.java:862) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.12.jar:5.3.12]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: org.springframework.vault.VaultException: Status 400 Bad Request: lease not found; nested exception is org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"errors":["lease not found"]}<LF>"
	at org.springframework.vault.client.VaultResponses.buildException(VaultResponses.java:64) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.VaultTemplate.doWithSession(VaultTemplate.java:451) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.lease.SecretLeaseContainer.doRenew(SecretLeaseContainer.java:729) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.lease.SecretLeaseContainer.doRenewLease(SecretLeaseContainer.java:670) ~[spring-vault-core-2.3.2.jar:2.3.2]
	... 11 common frames omitted
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"errors":["lease not found"]}<LF>"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101) ~[spring-web-5.3.12.jar:5.3.12]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168) ~[spring-web-5.3.12.jar:5.3.12]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.3.12.jar:5.3.12]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.12.jar:5.3.12]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.12.jar:5.3.12]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.12.jar:5.3.12]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.12.jar:5.3.12]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602) ~[spring-web-5.3.12.jar:5.3.12]
	at org.springframework.vault.core.lease.LeaseEndpoints.put(LeaseEndpoints.java:179) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.lease.LeaseEndpoints.access$300(LeaseEndpoints.java:38) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.lease.LeaseEndpoints$3.renew(LeaseEndpoints.java:100) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.lease.SecretLeaseContainer.lambda$doRenew$4(SecretLeaseContainer.java:729) ~[spring-vault-core-2.3.2.jar:2.3.2]
	at org.springframework.vault.core.VaultTemplate.doWithSession(VaultTemplate.java:448) ~[spring-vault-core-2.3.2.jar:2.3.2]
	... 13 common frames omitted
```

**Comment by thatsk** [comment]
@ivangfr does it intentional?

**Comment by thatsk** [comment]
when we are hitting https://github.com/ivangfr/springboot-vault-examples/blob/master/vault/config/config.hcl#L11 5min default ttl it shows this message and credentials got rotated in mysql

**Comment by ivangfr** [comment]
> @ivangfr does it intentional?

No, it is not intentional. This WARN log is from Spring Framework library.

**Comment by thatsk** [comment]
so its known issue and we can ignore it and it did not break the application connectivity on real time.

**Comment by thatsk** [comment]
i sawn when ttl has expired it give this warning

**Comment by ivangfr** [comment]
Yes, but the app is supposed to continue working fine. Maybe, we can hide the WARN logs by defining some log level to some packages

**Comment by ivangfr** [comment]
Hi @thatsk , in order to hide the WARN message, set the following in our `application.properties`
```
logging.level.org.springframework.vault=ERROR
```
I am closing the issue. Best
